include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = PhoneAuraStudio
PhoneAuraStudio_FILES = main.m PAStudioAppDelegate.m PAStudioRootController.m
PhoneAuraStudio_FRAMEWORKS = UIKit Contacts ContactsUI QuartzCore
PhoneAuraStudio_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
PhoneAuraStudio_INSTALL_PATH = /Applications

include $(THEOS_MAKE_PATH)/application.mk
