include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = PhoneAuraStudio
PhoneAuraStudio_FILES = main.m AppDelegate.m StudioViewController.m
PhoneAuraStudio_FRAMEWORKS = UIKit QuartzCore
PhoneAuraStudio_CFLAGS = -fobjc-arc
PhoneAuraStudio_INSTALL_PATH = /Applications

include $(THEOS_MAKE_PATH)/application.mk
