include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = UnlockVibratePrefs
UnlockVibratePrefs_FILES = UVRootListController.m
UnlockVibratePrefs_FRAMEWORKS = UIKit
UnlockVibratePrefs_PRIVATE_FRAMEWORKS = Preferences
UnlockVibratePrefs_INSTALL_PATH = /Library/PreferenceBundles
UnlockVibratePrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
