include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = PhoneAuraPrefs
PhoneAuraPrefs_FILES = PARootListController.m
PhoneAuraPrefs_FRAMEWORKS = UIKit
PhoneAuraPrefs_INSTALL_PATH = /Library/PreferenceBundles
PhoneAuraPrefs_CFLAGS = -fobjc-arc
PhoneAuraPrefs_LDFLAGS = -Wl,-undefined,dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
